### PR TITLE
Double all standalone faces and fix chain model

### PR DESCRIPTION
**Pull request by pschichtel**
* Standalone faces are problematic, when the rendering engine applies backface culling, leading to one-sided objects. I introduce a second face with reversed vertex winding order.
* I introduce a Chain model that properly scales the model and correctly maps the texture.

### CODE REVIEW

**Comment by pschichtel** [comment]
image
that's how this looks in unity

**Comment by mmdanggg2** [comment]
Thanks for the patch. If we're adding it, I think the doubled surfaces should be an optional setting. It seems like a hack just to fake backsided rendering. Most programs can or do have backfaces enabled so this should be disabled by default.

**Comment by pschichtel** [comment]
@mmdanggg2 I totally agree. I quickly fixed this because I intent do use your tool during the Ludum Dare 48 over the weekend in conjunction with Unity. So after the weekend I can work on making it optional.

Btw I noticed that that your project does not explicitly state a license, is that intentional?

**Comment by pschichtel** [comment]
@mmdanggg2 Added the option to enable/disable the backface generation and it also reverses the UVs now (e.g. plant backfaces showed rotated textures)

The tool proved to be pretty effective: https://ldjam.com/events/ludum-dare/48/drillromantik

**Comment by mmdanggg2** [comment]
Many thanks. I've just renamed a couple things. Good luck with the Ludum Dare!

**Pull request merged**
