### PR TITLE
Optimisation

### PR DESCRIPTION
**Pull request by mmdanggg2**
Complete rewrite of optimisation code, needs thorough testing but it is working great so far.

### CODE REVIEW

**Comment by paol** [comment]
Great work, a generic mechanism that works on all faces is exactly what we needed.
On my test world everything works correctly, however when I exported a giant chunk of a server world I have (I wanted to compare export times and output sizes with and w/o optimization) I got this error:

ERROR: Error while exporting OBJ:
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.jmc.OBJOutputFile.mergeFaces(OBJOutputFile.java:629)
	at org.jmc.OBJOutputFile.mergeAxisFaces(OBJOutputFile.java:541)
	at org.jmc.OBJOutputFile.addChunkBuffer(OBJOutputFile.java:486)
	at org.jmc.ObjExporter.export(ObjExporter.java:188)
	at org.jmc.gui.ExportWindow$9$2.run(ExportWindow.java:751)
	at java.lang.Thread.run(Thread.java:745)

Line 629 is this one:
UV uvVec2 = UV.subtract(face2.uvs[verts2MatchIndex.get(1)], uv2);

(Unrelated note: verts1MatchIndex and verts2MatchIndex seem to have fixed size, if that's the case then it's slightly faster and more readable to use int[] instead of ArrayList<Integer>)

**Comment by mmdanggg2** [comment]
That should have fixed it, I think it was caused by floating point rounding errors when checking if a vertex was equal

**Comment by paol** [comment]
Seems to be fixed.

**Comment by danijel3** [comment]
Awesome work guys. I haven't had time to check it out myself, but do you want me to update the download on the site?

**Pull request merged**
