### PR TITLE
Add ID mappings for mushroom blocks and mycelium

### PR DESCRIPTION
**Pull request by ILikePlayingGames**
One step towards #209

### CODE REVIEW

**Comment by ILikePlayingGames** [comment]
BTW, is there a way to import the original states from the world instead of setting a static state?

**Comment by mmdanggg2** [comment]
Thanks for pointing that out.
Pre 1.13, blocks only had the data values byte, that's all we have to calculate block states.

**Comment by ILikePlayingGames** [comment]
@mmdanggg2 Thanks! Would it be possible to add a warning when a block doesn’t have a texture?  When I was rendering the preview the mushroom showed purple but I didn’t see any console warnings.

**Comment by mmdanggg2** [comment]
I've added a debug log for when a texture couldn't be found for a block so that should help that specific situation.

That alerted me that observers were not converted correctly so that's fixed too now. And on top of that the observers resource pack model was not computed correctly so I've fixed an issue with the model readier too which affected a couple of blocks; very helpful little rabbit hole!

**Pull request closed without merging**
