### PR TITLE
Exporting user generated ItemFrames with individual texture

### PR DESCRIPTION
**Pull request by begner**
Exporting user generated ItemFrames with individual texture

### CODE REVIEW

**Comment by danijel3** [comment]
I added you as a contributor now. Feel free to commit straight to the project.

**Comment by Moonlight63** [comment]
??? wrong person, lol

**Comment by jmc2obj** [comment]
Wrong person what? Can you please explain?

**Comment by Moonlight63** [comment]
I have been a contributor. I think you were trying to add begner

**Comment by jmc2obj** [comment]
You are both added. 

I commented on the pull request. Not sure why you also got the message. I hope he did as well.

**Comment by Moonlight63** [comment]
oh, lol I see, thats funny. good to know anyway cuz I'll have a commit
tonight aswell, haha.

**Comment by begner** [comment]
Yeah - ill think of an xml Conf for that Color thing... (Cause colors has changed in a specific mc Version...) - but it was too Late yesterday

**Comment by begner** [comment]
Thanks for the contribution state...

Im new to Java - so please feel free to correct my Code :)

Next thing in my List are Amor-stands and Banners...

And better cycles support...

**Pull request merged**
